rules = [
  NoAutoTupling,
  NoValInForComprehension,
  OrganizeImports,
  RedundantSyntax,
  RemoveUnused,
]

OrganizeImports {
  groupedImports = AggressiveMerge,
  targetDialect = Scala3,
}

RemoveUnused.imports = false
